org: adrianurbinamendoza
service: api-pelicula

provider:
  name: aws
  runtime: python3.13
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::254780740814:role/LabRole
  environment:
    TABLE_NAME: ${sls:stage}-t_peliculas

functions:
  crear:
    handler: CrearPelicula2.lambda_handler
    events:
      - http:
          path: /pelicula/crear2
          method: post
          cors: true
          integration: lambda

resources:
  Resources:
    TablaPeliculas:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: uuid
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
